### ISSUE TITLE
New version of Flask is not supported 

### ISSUE THREAD

**Issue by Aspect26** [AtteqCom/zsl#115]
```
Traceback (most recent call last):
   File "app.py", line 63, in application
     initialize()
   File "app.py", line 48, in initialize
     app = Zsl(app_name, version=__version__, modules=MarblegameWebServiceContainer.modules())
   File "/usr/local/lib/python3.6/site-packages/zsl/application/service_application.py", line 91, in __init__
     self._configure_injector(modules)
   File "/usr/local/lib/python3.6/site-packages/zsl/application/service_application.py", line 159, in _configure_injector
     self._bind_modules(modules)
   File "/usr/local/lib/python3.6/site-packages/zsl/application/service_application.py", line 196, in _bind_modules
     self.injector.binder.install(module)
   File "/usr/local/lib/python3.6/site-packages/injector.py", line 388, in install
     instance(self)
   File "/usr/local/lib/python3.6/site-packages/injector.py", line 622, in __call__
     self.configure(binder)
   File "/usr/local/lib/python3.6/site-packages/zsl/application/modules/logger_module.py", line 22, in configure
     self.configure_logging()
   File "/usr/local/lib/python3.6/site-packages/zsl/utils/injection_helper.py", line 53, in _inject
     return ff(*args, **dependencies)
   File "/usr/local/lib/python3.6/site-packages/zsl/application/modules/logger_module.py", line 34, in configure_logging
     self._recreate_app_logger(app)
   File "/usr/local/lib/python3.6/site-packages/zsl/application/modules/logger_module.py", line 38, in _recreate_app_logger
     del logging.getLogger(app.logger_name).manager.loggerDict[app.logger_name]
 AttributeError: 'ServiceApplication' object has no attribute 'logger_name'
```

Class Flask (from which our ServiceApplication class inherits) no longer contains attribute `logger_name` since 1.0 version of Flask

**Comment by babky** [comment]
fixed by merging https://github.com/AtteqCom/zsl/pull/120
